debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  port: 15000

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/metamate
    username: admin
    password: admin
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  thymeleaf:
    cache: false # Set to true for production; false for development (disabled caching for faster development)
    mode: HTML5
    encoding: UTF-8


  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
    show-sql: true

  sql.init.mode: always

  data.rest:
    base-path: /api
    detection-strategy: annotated

  thymeleaf3.decoupled-logic: true